"use client";

import React from "react";
import {
  Wallet,
  Laptop,
  TrendingUp,
  Building,
  Home,
  Plus,
  Car,
  ShoppingBag,
  Zap,
  Film,
  UtensilsCrossed,
  HeartPulse,
  GraduationCap,
  Smile,
  Plane,
  Shield,
  Gift,
  Receipt,
  MoreHorizontal,
  Coffee,
  Dumbbell,
  Briefcase,
  Music,
  BookOpen,
  Smartphone,
  Sparkles,
  Dog,
  Shirt,
  Scissors,
  Fuel,
  PiggyBank,
  DollarSign,
  Tag,
  CreditCard,
  Tv,
  Bus,
  Train,
  Camera,
  Wrench,
  Stethoscope,
  Lightbulb,
} from "lucide-react";

export const ICON_MAP = {
  Wallet,
  Laptop,
  TrendingUp,
  Building,
  Home,
  Plus,
  Car,
  Shopping: ShoppingBag,
  ShoppingBag,
  Zap,
  Film,
  UtensilsCrossed,
  HeartPulse,
  GraduationCap,
  Smile,
  Plane,
  Shield,
  Gift,
  Receipt,
  MoreHorizontal,
  Coffee,
  Dumbbell,
  Briefcase,
  Music,
  BookOpen,
  Smartphone,
  Sparkles,
  Dog,
  Shirt,
  Scissors,
  Fuel,
  PiggyBank,
  DollarSign,
  CreditCard,
  Tv,
  Bus,
  Train,
  Camera,
  Wrench,
  Stethoscope,
  Lightbulb,
  Tag,
};

export const AVAILABLE_ICONS = [
  { name: "Tag", label: "Tag" },
  { name: "ShoppingBag", label: "Shopping" },
  { name: "UtensilsCrossed", label: "Food & Dining" },
  { name: "Coffee", label: "Coffee / Drinks" },
  { name: "Home", label: "Housing / Home" },
  { name: "Car", label: "Vehicle / Transport" },
  { name: "Fuel", label: "Fuel / Gas" },
  { name: "Zap", label: "Electricity / Utility" },
  { name: "Receipt", label: "Bills & Invoices" },
  { name: "HeartPulse", label: "Health / Medical" },
  { name: "GraduationCap", label: "Education" },
  { name: "Film", label: "Entertainment" },
  { name: "Music", label: "Music & Streaming" },
  { name: "Tv", label: "TV & Subscriptions" },
  { name: "Plane", label: "Travel & Vacation" },
  { name: "Dumbbell", label: "Fitness & Gym" },
  { name: "Dog", label: "Pets" },
  { name: "Gift", label: "Gifts & Charity" },
  { name: "Smartphone", label: "Phone / Electronics" },
  { name: "Shirt", label: "Clothing / Fashion" },
  { name: "Scissors", label: "Personal Care" },
  { name: "BookOpen", label: "Books & Study" },
  { name: "Wallet", label: "Salary / Income" },
  { name: "Briefcase", label: "Work / Business" },
  { name: "TrendingUp", label: "Investments" },
  { name: "Building", label: "Real Estate / Office" },
  { name: "PiggyBank", label: "Savings" },
  { name: "CreditCard", label: "Banking" },
  { name: "Sparkles", label: "Miscellaneous" },
];

export function CategoryIcon({ name, className = "h-4 w-4", style }) {
  if (!name) return <Tag className={className} style={style} />;

  // Normalize key name (case-insensitive match)
  const normalizedKey = Object.keys(ICON_MAP).find(
    (k) => k.toLowerCase() === name.toLowerCase()
  );

  const IconComponent = normalizedKey ? ICON_MAP[normalizedKey] : Tag;
  return <IconComponent className={className} style={style} />;
}

export default CategoryIcon;
